name=dv_iir_filter8
version=1.0.0
author=David Vandensteen
maintainer=David Vandensteen <dvandensteen@gmail.com>
sentence=8-bit IIR filter API with fixed-point internal processing.
paragraph=IIR filter for smoothing 8-bit data using progressive linear interpolation.
category=Signal Input/Output
url=https://github.com/David-Vandensteen/dv-iir-filter8
architectures=*
includes=dv_iir_filter8.h